# Generated by Django 3.2 on 2021-06-04 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 16, 22, 0, 131582, tzinfo=utc), verbose_name='Time published'),
        ),
    ]
